#!/bin/bash

#!/bin/bash
[[ -e /etc/ADM-db/idioma_menuinst ]] && tr=$(cat < /etc/ADM-db/idioma_menuinst)

prices_on () {
[[ -z ${callback_query_from_first_name} ]] && firsnme="${message_from_first_name}" || firsnme="${callback_query_from_first_name}"
[[ -z ${callback_query_from_last_name} ]] && lastnme="${message_from_last_name}" || lastnme="${callback_query_from_last_name}"
local msg
          msg=' -=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=-
\n'
		  msg+=" Hola, 『 ${firsnme} ${lastnme} 』 \n"
		  msg+=' -=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=-
\n' 
          msg+=' $721 ARS - Acceso ilimitado al BOT 4 días \n'
          msg+=' $1,030 ARS - Acceso ilimitado al BOT 7 días \n'
          msg+=' $1,545 ARS - Acceso ilimitado al BOT 15 días \n'
          msg+=' $2,060 ARS - Acceso ilimitado al BOT 30 días \n'
          msg+=' $3,090 ARS - Acceso ilimitado al BOT 60 días\n'
          msg+=' $4,120 ARS - Acceso ilimitado al BOT 90 días\n'
          msg+=' $5,150 ARS - Acceso ilimitado al BOT 180 días\n'
          msg+=' $9,270 ARS - Acceso ilimitado al BOT 365 días\n'
		  msg+='-=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=-
\n' 
		  msg+=" BOT PREMIUM CON ACCESO Ilimitado \n Incluyendo tu reseller en la Key! \n Soporte, Actualizaciones y MAS!!)\n"
		  msg+='-=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=-
\n'  
		  msg+=" VISITA NUESTRO CATALOGO EN https://t.me/joaquinH2 \n"
		  msg+='-=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=-
\n'  
          ShellBot.sendMessage	--chat_id "${message_chat_id[$id]}" \
							--reply_to_message_id "${message_message_id[$id]}" \
							--text "<i>$(echo -e $msg)</i>" \
							--parse_mode html
return 0
}
